export const fishTypes = [
  "Betta Fish",
  "Goldfish",
  "Guppy",
  "Angelfish",
  "Neon Tetra",
  "Molly",
  "Swordtail",
  "Platies",
  "Koi Fish",
  "Discus Fish",
  "Cichlid",
  "Oscar Fish",
  "Siamese Fighting Fish",
  "Clownfish",
  "Zebra Danio",
  "Other",
];

export const dogTypes = [
  "Labrador Retriever",
  "BitBull",
  "German Shepherd",
  "Golden Retriever",
  "French Bulldog",
  "Bulldog",
  "Beagle",
  "Poodle",
  "Rottweiler",
  "Yorkshire Terrier",
  "Boxer",
  "Siberian Husky",
  "Dachshund",
  "Doberman Pinscher",
  "Shih Tzu",
  "Australian Shepherd",
  "Other",
];

export const catTypes = [
  "Persian Cat",
  "Maine Coon",
  "Siamese Cat",
  "Ragdoll Cat",
  "British Shorthair",
  "Bengal Cat",
  "Sphynx Cat",
  "Scottish Fold",
  "Russian Blue",
  "Abyssinian Cat",
  "Birman Cat",
  "Burmese Cat",
  "Norwegian Forest Cat",
  "Exotic Shorthair",
  "American Shorthair",
  "Other",
];

export const horseTypes = [
  "Arabian Horse",
  "Thoroughbred",
  "Quarter Horse",
  "Paint Horse",
  "Appaloosa",
  "Morgan Horse",
  "Tennessee Walking Horse",
  "Miniature Horse",
  "Friesian Horse",
  "Andalusian Horse",
  "Shetland Pony",
  "Clydesdale Horse",
  "Welsh Pony",
  "Mustang Horse",
  "Haflinger Horse",
  "Other",
];

export const sheepTypes = [
  "Suffolk Sheep",
  "Dorset Sheep",
  "Merino Sheep",
  "Rambouillet Sheep",
  "Hampshire Sheep",
  "Southdown Sheep",
  "Cheviot Sheep",
  "Lincoln Sheep",
  "Columbia Sheep",
  "Shropshire Sheep",
  "Assaf Sheep",
  "Droper Sheep",
  "Other",
];

export const chickenTypes = [
  "Rhode Island Red",
  "Leghorn",
  "Plymouth Rock",
  "Sussex Chicken",
  "Wyandotte",
  "Other",
];

export const parrotsTypes = [
  "African Grey Parrot",
  "Amazon Parrot",
  "Budgerigar",
  "Caique",
  "Cockatiel",
  "Conure",
  "Eclectus Parrot",
  "Lovebird",
  "Macaw",
  "Parakeet",
  "Quaker Parrot",
  "Senegal Parrot",
  "Other",
];
