export const electricProducts = [
    'Refrigerator',
    'Washing Machine',
    'Air Conditioner',
    'Microwave Oven',
    'Electric Kettle',
    'Toaster',
    'Blender',
    'Juicer',
    'Electric Cooker',
    'Electric Grill',
    'Coffee Maker',
    'Electric Fan',
    'Hair Dryer',
    'Electric Shaver',
    'Electric Toothbrush',
    'Electric Heater',
    'Electric Iron',
    'Vacuum Cleaner',
    'Electric Mixer',
    'Electric Skillet',
    'Dishwasher',
    'Electric Oven',
    'Electric Stove',
    'Electric Pressure Cooker',
    'Electric Smoker',
    'Electric Steamer',
    'Food Processor',
    'Electric Can Opener',
    'Electric Knife',
    'Electric Fireplace'
  ];
  
  export const cellularDevices = [
    'iPhone 13',
    'Samsung Galaxy S21',
    'Google Pixel 6',
    'OnePlus 10',
    'Xiaomi Mi 12',
    'Huawei P50 Pro',
    'Sony Xperia 1 III',
    'iPhone SE (2022)',
    'Samsung Galaxy Note 20',
    'Google Pixel 5a',
    'OnePlus 9 Pro',
    'Xiaomi Redmi Note 11',
    'Huawei Mate 40 Pro',
    'Sony Xperia 5 III',
    'iPhone 12 Mini',
    'Samsung Galaxy A52',
    'Google Pixel 4a',
    'OnePlus Nord 2',
    'Xiaomi Poco X3',
    'Huawei Nova 7',
    'Sony Xperia 10 III',
    'iPhone 11',
    'Samsung Galaxy S20 FE',
    'Google Pixel 4',
    'OnePlus 8T',
    'Xiaomi Mi 11 Lite',
    'Huawei Y9a',
    'Sony Xperia L4',
    'iPhone XR',
    'Samsung Galaxy A71'
  ];
  
  export const furnitureItems = [
    'Sofa',
    'Bed',
    'Dining Table',
    'Coffee Table',
    'Wardrobe',
    'Bookshelf',
    'Desk',
    'Dresser',
    'Nightstand',
    'Couch',
    'Armchair',
    'TV Stand',
    'Cabinet',
    'Shoe Rack',
    'Console Table',
    'Futon',
    'Sectional Sofa',
    'Recliner',
    'Bean Bag Chair',
    'Bunk Bed',
    'Rocking Chair',
    'Bar Stool',
    'Storage Bench',
    'Chaise Lounge',
    'Patio Furniture Set',
    'Dining Chair',
    'Kitchen Island',
    'End Table',
    'Office Chair',
    'Computer Desk'
  ];

  export const sportItems = [
    'Basketball',
    'Soccer Ball',
    'Football',
    'Volleyball',
    'Tennis Racket',
    'Golf Clubs',
    'Baseball Bat',
    'Hockey Stick',
    'Cricket Bat',
    'Table Tennis Paddle',
    'Badminton Racket',
    'Swimming Goggles',
    'Yoga Mat',
    'Jump Rope',
    'Boxing Gloves',
    'Martial Arts Gi',
    'Running Shoes',
    'Cycling Helmet',
    'Dumbbells',
    'Resistance Bands',
    'Exercise Ball',
    'Skipping Rope',
    'Treadmill',
    'Elliptical Trainer',
    'Bicycle',
    'Rowing Machine',
    'Punching Bag',
    'Gymnastics Rings',
    'Kettlebell',
    'Balance Board'
  ];
export const babyChildItems = [
    'Diapers',
    'Baby Wipes',
    'Baby Clothes',
    'Baby Shoes',
    'Baby Bottle',
    'Pacifier',
    'Baby Blanket',
    'Baby Monitor',
    'Stroller',
    'Car Seat',
    'High Chair',
    'Baby Carrier',
    'Crib',
    'Changing Table',
    'Baby Bath Tub',
    'Baby Toys',
    'Baby Books',
    'Baby Thermometer',
    'Child Safety Gate',
    'Baby Food Maker',
    'Baby Bouncer',
    'Playpen',
    'Baby Walker',
    'Toddler Bed',
    'Kids Table and Chairs',
    'Toy Chest',
    'Kids Bookshelf',
    'Kids Desk',
    'Childrens Clothing',
    'Childrens Shoes'
  ];
    
  export const computerItems = [
    'Desktop Computer',
    'Laptop',
    'Monitor',
    'Keyboard',
    'Mouse',
    'Printer',
    'Scanner',
    'External Hard Drive',
    'USB Flash Drive',
    'Router',
    'Modem',
    'Wi-Fi Range Extender',
    'Ethernet Cable',
    'Webcam',
    'Headphones',
    'Microphone',
    'Speakers',
    'Graphics Card',
    'RAM',
    'SSD',
    'HDD',
    'Motherboard',
    'Power Supply Unit',
    'CPU',
    'Computer Case',
    'Cooling Fan',
    'Docking Station',
    'UPS',
    'KVM Switch',
    'Computer Desk'
  ];
  
  export const homeGardenItems = [
    'Lawn Mower',
    'Garden Hose',
    'Rake',
    'Shovel',
    'Gardening Gloves',
    'Pruning Shears',
    'Watering Can',
    'Wheelbarrow',
    'Outdoor Furniture',
    'Grill',
    'Patio Umbrella',
    'Outdoor Lighting',
    'Plant Pots',
    'Garden Bench',
    'Hammock',
    'Bird Feeder',
    'Compost Bin',
    'Pressure Washer',
    'Garden Cart',
    'Garden Tool Set',
    'Sun Lounger',
    'Gazebo',
    'Fire Pit',
    'Leaf Blower',
    'Outdoor Storage Box',
    'Garden Trellis',
    'Pond Pump',
    'Greenhouse',
    'Sprinkler System',
    'Outdoor Playset'
  ];
  
  